version: '3.9'

services:
  php83:
    build:
      context: .infrastructure/.docker
      dockerfile: Dockerfile
      args:
        from_image: php:8.3-fpm-alpine
    working_dir: /app
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin"
    volumes:
      - ./:/app
  php82:
    working_dir: /app
    build:
      context: .infrastructure/.docker
      dockerfile: Dockerfile
      args:
        from_image: php:8.2-fpm-alpine
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin"
    volumes:
      - ./:/app
  php81:
    build:
      context: .infrastructure/.docker
      dockerfile: Dockerfile
      args:
        from_image: php:8.1-fpm-alpine
    working_dir: /app
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin"
    volumes:
      - ./:/app
